version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: epm_web
    ports:
      - "8081:80"
    volumes:
      - ./src/public:/var/www/html
      - ./src:/var/www/src
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.env:/var/www/.env
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - DB_HOST=db
      - DB_NAME=epm_congress
      - DB_USER=epm_user
      - DB_PASSWORD=epm_password
      - DB_PORT=3306
      - APP_ENV=development
      - APP_DEBUG=true
      - APP_URL=http://localhost:8081
      - SITE_NAME=EPM CONGRESS 2025
    networks:
      - epm_network
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: epm_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: epm_congress
      MYSQL_USER: epm_user
      MYSQL_PASSWORD: epm_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/database:/docker-entrypoint-initdb.d
    networks:
      - epm_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  epm_network:
    driver: bridge
